import { Component, Output, OnInit, EventEmitter } from '@angular/core'
import { AddNewUserService } from 'src/services/add-new-user.service'
import { TriggerRefetchUsersService } from 'src/services/trigger-refetch-users.service'

@Component({
    selector: 'app-add-user-modal',
    templateUrl: './add-user-modal.component.html',
    styleUrls: ['./add-user-modal.component.scss'],
})
export class AddUserModalComponent implements OnInit {
    @Output() notify = new EventEmitter()
    password: string = ''
    username: string = ''
    firstname: string = ''
    lastname: string = ''
    showPassword: boolean = false

    constructor(
        private addUserService: AddNewUserService,
        private triggerRefetchUsersService: TriggerRefetchUsersService
    ) {}

    ngOnInit() {}

    triggerCloseModal() {
        this.notify.emit()
    }

    submitUser() {
        this.addUserService
            .createNewUser({
                id: 0, //auto increment id is generated by backend, so no effects here
                password: this.password,
                login: this.username,
                firstname: this.firstname,
                lastname: this.lastname,
            })
            .subscribe(() => {
                //user refetch in table on data change
                this.triggerRefetchUsersService.triggerUserRefetch()
            })
        this.triggerCloseModal()
    }

    toggleShowPassword() {
        this.showPassword = !this.showPassword
    }
}
